// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package spark

import (
	"spark/api/spark"
)

type ControllerV1 struct{}

func NewV1() spark.ISparkV1 {
	return &ControllerV1{}
}
