// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package spark

import (
	"spark/api/spark"
)

type ControllerV1 struct{}

func NewV1() spark.ISparkV1 {
	return &ControllerV1{}
}

type ControllerV2 struct{}

func NewV2() spark.ISparkV2 {
	return &ControllerV2{}
}

type ControllerV3 struct{}

func NewV3() spark.ISparkV3 {
	return &ControllerV3{}
}
